version: '2'
services:
  node1:
    environment:
      - NAME=1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
    volumes:
    - ./data1:/data
  node2:
    environment:
      - PEERS=ws://node1:6001
      - NAME=2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    volumes:
    - ./data2:/data
    links:
      - node1:node1
  node3:
    environment:
      - PEERS=ws://node2:6001
      - NAME=3
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3003:3001"
    volumes:
    - ./data3:/data
    links:
      - node2:node2
